accepted = [
  "Apache-2.0",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "CC0-1.0",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "Apache-2.0 WITH LLVM-exception",
]

targets = ["x86_64-unknown-linux-musl"]
ignore-build-dependencies = false
ignore-dev-dependencies = false
ignore-transitive-dependencies = false
