[graph]
targets = ["x86_64-unknown-linux-musl"]

[advisories]
unmaintained = "workspace"
yanked = "deny"

[licenses]
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "CC0-1.0",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "Apache-2.0 WITH LLVM-exception",
]
confidence-threshold = 0.93

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
