[graph]
targets = ["x86_64-unknown-linux-musl"]

[advisories]
unmaintained = "workspace"
yanked = "deny"

[licenses]
allow = [
  "Apache-2.0",
  "MIT",
]
confidence-threshold = 0.93

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
