#!/usr/bin/env python3
"""Audit Cargo licenses and assemble notices for build archives and images."""

from __future__ import annotations

import shutil
import subprocess
import os
import tempfile
from pathlib import Path

from check_pdf_assets import check as check_pdf_assets


MARKER = "Generated by scripts/build_license_bundle.py. Safe to recreate.\n"


def run(command: list[str], cwd: Path) -> str:
    try:
        completed = subprocess.run(
            command,
            cwd=cwd,
            check=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            capture_output=True,
        )
    except subprocess.CalledProcessError as error:
        detail = error.stderr or error.stdout or str(error)
        for name in (
            "DATABASE_URL", "PUFFINBOX_DATABASE_URL", "POSTGRES_PASSWORD",
            "PUFFINBOX_BOOTSTRAP_ADMIN_PASSWORD", "PUFFINBOX_SETUP_TOKEN",
        ):
            secret = os.environ.get(name)
            if secret:
                detail = detail.replace(secret, "[redacted]")
        raise SystemExit(f"License command failed ({' '.join(command)}):\n{detail.strip()}") from error
    return completed.stdout.strip()


def copy_required(source: Path, destination: Path) -> None:
    if not source.is_file():
        raise SystemExit(f"Required license or attribution file is missing: {source}")
    shutil.copyfile(source, destination)


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    pdf_manifest = check_pdf_assets(root)
    output = root / "dist" / "licenses"
    parent = output.parent
    parent.mkdir(parents=True, exist_ok=True)
    if parent.is_symlink() or parent.resolve() != root / "dist" or output.resolve() != output:
        raise SystemExit("The license bundle output path must resolve to the in-repository dist/licenses directory.")
    if output.is_symlink():
        raise SystemExit("Refusing to recreate a symlinked dist/licenses output directory.")
    if output.exists():
        marker = output / ".generated-by-puffinbox"
        if not marker.is_file() or marker.read_text(encoding="utf-8") != MARKER:
            raise SystemExit("Refusing to replace dist/licenses because it is not marked as generated output.")

    staging = Path(tempfile.mkdtemp(prefix=".licenses-build-", dir=parent))
    backup = None
    try:
        run(["cargo", "fetch", "--locked"], root)
        run(["cargo", "deny", "--locked", "check"], root)
        run(["cargo", "about", "generate", "--locked", "--output-file", str(staging / "RUST_DEPENDENCY_LICENSES.md"), "third-party.hbs"], root)

        copy_required(root / "LICENSE-MIT", staging / "LICENSE-MIT")
        copy_required(root / "LICENSE-APACHE", staging / "LICENSE-APACHE")
        copy_required(root / "THIRD_PARTY_NOTICES.md", staging / "PROJECT_THIRD_PARTY_NOTICES.md")
        copy_required(root / "vendor" / "notices" / "MIMETYPEMAP-MIT.txt", staging / "MIMETYPEMAP-LICENSE.txt")
        copy_required(root / "vendor" / "notices" / "MIME-DB-MIT.txt", staging / "MIME-DB-LICENSE.txt")
        copy_required(root / "vendor" / "notices" / "tracing-subscriber-datetime-MIT.txt", staging / "TRACING-DATETIME-MIT.txt")
        copy_required(root / "web" / "vendor" / "hls.js-LICENSE.txt", staging / "HLS-JS-LICENSE.txt")
        copy_required(root / "web" / "vendor" / "README.md", staging / "HLS-JS-PROVENANCE.md")
        pdf_notices = staging / "PDF-JS"
        pdf_notices.mkdir()
        pdf_root = root / "web" / "vendor" / "pdfjs"
        for name in ["README.md", "provenance.json", *pdf_manifest["licenseFiles"]]:
            destination = pdf_notices / name
            destination.parent.mkdir(parents=True, exist_ok=True)
            copy_required(pdf_root / name, destination)
        copy_required(Path("/usr/share/doc/musl/copyright"), staging / "MUSL-COPYRIGHT")

        sysroot = Path(run(["rustc", "--print", "sysroot"], root))
        rust_docs = sysroot / "share" / "doc" / "rust"
        copy_required(rust_docs / "COPYRIGHT-library.html", staging / "RUST-STANDARD-LIBRARY-COPYRIGHT.html")
        copy_required(rust_docs / "COPYRIGHT.html", staging / "RUST-TOOLCHAIN-COPYRIGHT.html")
        (staging / ".generated-by-puffinbox").write_text(MARKER, encoding="utf-8")

        if output.exists():
            backup = parent / f".licenses-backup-{staging.name.removeprefix('.licenses-build-')}"
            os.replace(output, backup)
        try:
            os.replace(staging, output)
        except OSError:
            if backup is not None and backup.exists() and not output.exists():
                os.replace(backup, output)
            raise
        if backup is not None:
            shutil.rmtree(backup)
        print(f"Audited Cargo dependencies and generated full notices in {output}")
    except BaseException:
        if staging.exists() and staging.parent.resolve() == parent.resolve() and staging.name.startswith(".licenses-build-") and not staging.is_symlink():
            shutil.rmtree(staging)
        raise
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
